name: nggc
description: "New Generation Gospel Church Sunday School App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: 9.0.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.0
  share_plus: ^12.0.2
  shimmer: ^3.0.0
  package_info_plus: ^8.1.0
  screenshot: ^3.0.0
  auto_size_text: ^3.0.0
  permission_handler: ^11.3.1
  open_file: ^3.5.7
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  audioplayers: ^6.4.0
  video_player: ^2.9.5
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/nggc-logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/nggc-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bible_bg/
    - assets/bibles/
    - assets/manuals/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700